name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t bpimg -f docker/Dockerfile .
      
    - name: Build the proposal
      run: docker run --rm -v "$PWD":/bp bpimg sh /bp/docker/render_thesis.sh voorstel

    - name: Build the thesis
      run: docker run --rm -v "$PWD":/bp bpimg sh /bp/docker/render_thesis.sh bachproef

    - name: Build the poster
      run: docker run --rm -v "$PWD":/bp bpimg sh /bp/docker/render_thesis.sh poster

    - uses: actions/upload-artifact@v4
      name: Upload artifacts
      with:
        name: output
        path: |
          output/*.pdf
          output/*.log
        if-no-files-found: error
